projects:
  Codegen Project:
    schemaPath: schema.json
    includes:
      - src/graphql/**/*.ts
    excludes:
      - ./amplify/**
      - src/API.ts
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/API.ts
        docsFilePath: src/graphql
        region: eu-central-1
        apiId: <<ANONYMIZED>>
        frontend: javascript
        framework: none
        maxDepth: 2
extensions:
  amplify:
    version: 3
